### ISSUE TITLE
Unrecognized cigar character 'N' from cigar component

### ISSUE THREAD

**Issue by ajtonsager** [caozhichongchong/QuickVariants#3]
Hello,

I've mapped my whole genome sequencing reads from S.cerevisiae to the yeast genome using HISAT2 to generate my .sam files. I've set up a brand new conda environment with java and quickvariants as described in this Github. Unfortunately, I run into an issue with each of my four tester .sam files as depicted below:

`Exception in thread "Thread-0" java.lang.RuntimeException: Failed to process [GCTTAGCCTGCGCTTAGCCTACAACTTCTTCCGCTCTCGAAAAGACCAATATAATAGAAAGTTATAAATTACATTTCCTTATTAGGTATA
CGACCTCGCGCTTCGAAGTAGAGGAGCCCTTTTTGGCGTACCTACATATGGCGCGTCAGA ACCCATTCACCCACGACGTATCAAGTTACTTCCTTGGTGCAATGTCCCACTATAAAAAAATTCCTTGACGCTAGATCGTTGGACTAAAATCTGCGTCACAATCGCCT
ACACAGGAAATATTGCCTATTTTCGTACAAGGTTACTTCCTAG ]
        at mapper.AlignerWorker.process(AlignerWorker.java:108)
        at mapper.AlignerWorker.run(AlignerWorker.java:83)
Caused by: java.lang.IllegalArgumentException: Unrecognized cigar character 'N' from cigar component '5535N' from full cigar string '138M5535N12M'
        at mapper.SamAlignment.toSequenceAlignment(SamAlignment.java:57)
        at mapper.AlignerWorker.tryConvertSamAlignment(AlignerWorker.java:188)
        at mapper.AlignerWorker.align(AlignerWorker.java:175)
        at mapper.AlignerWorker.process(AlignerWorker.java:106)
        ... 1 more
Worker failed; aborting
`

The java script appears to run into issues when "N" is in the cigar string -- any idea how I can still use the tool for my sam files? Thanks in advance!

**Comment by ajtonsager** [comment]
That would be wonderful! Thanks for the prompt response.

**Comment by mathjeff** [comment]
This should be done now in version 1.1.0!

Thanks for the report - sorry it took so long as we've been moving countries and institutions.
